# Generated by Django 5.2.8 on 2025-11-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Enter Product Name', max_length=50)),
                ('price', models.IntegerField(help_text='Enter Product Price')),
                ('mfg_date', models.DateField(help_text='Manufacture Date')),
                ('product_code', models.CharField(help_text='Enter Product Code')),
            ],
        ),
    ]
